- tests/Yaapii.Atoms.Tests/Primitives/DoubleOfTests.cs
No Test for DoubleOf
Test for DoubleOf exists
expected bug is not in DoubleOf class
> Bug DoubleOf test

- src/Yaapii.Atoms/Text/TextOf.cs
- tests/Yaapii.Atoms.Tests/Text/TextOfTest.cs
> Feat issue 48

- src/Yaapii.Atoms/List/Joined.cs
- tests/Yaapii.Atoms.Tests/List/JoinedTest.cs
#60 
Joint can join a list and single items
#closes 60
> Adds new ctor for Joined to concat a list and single items

- src/Yaapii.Atoms/Enumerator/ContainsEnumerator.cs
- tests/Yaapii.Atoms.Tests/Enumerable/ContainsTest.cs
- tests/Yaapii.Atoms.Tests/Enumerator/ContainsEnumeratorTest.cs
#103 
Contains of emty list returns false
> Empty Contains

- src/Yaapii.Atoms/Func/ActionWithFallback.cs
- src/Yaapii.Atoms/Func/BiFuncWithFallback.cs
- src/Yaapii.Atoms/Func/FuncWithFallback.cs
- tests/Yaapii.Atoms.Tests/Func/ActionWithFallbackTest.cs
- tests/Yaapii.Atoms.Tests/Func/BiFuncWithFallbackTest.cs
- tests/Yaapii.Atoms.Tests/Func/FuncWithCallbackTest.cs
#101 
Now we have:
- `FuncWithFallback<Out>`
- `ActionWithFallback`
- `ActionWithFallback<In>`
- `BiFuncWithFallback<In1, In2, Out>`
> I101 func with fallback

- build.cake
- src/Yaapii.Atoms/Yaapii.Atoms.csproj
- tests/Yaapii.Atoms.Tests/Yaapii.Atoms.Tests.csproj
closes #102
#102 
Using .NET Standard 2.0
> Migrate to .NETStandard 2.0

- build.cake
- src/Yaapii.Atoms/Collection/Reversed.cs
- src/Yaapii.Atoms/Collection/SyncCollection.cs
- src/Yaapii.Atoms/Enumerable/Reduced.cs
- src/Yaapii.Atoms/Enumerator/MappedEnumerator.cs
- src/Yaapii.Atoms/Func/BiFuncOf.cs
- src/Yaapii.Atoms/Func/BiFuncWithFallback.cs
- src/Yaapii.Atoms/Func/FuncWithFallback.cs
- src/Yaapii.Atoms/Func/StickyBiFunc.cs
- src/Yaapii.Atoms/IBiFunc.cs
- src/Yaapii.Atoms/IO/InputStreamOf.cs
- src/Yaapii.Atoms/IO/OutputStreamTo.cs
- src/Yaapii.Atoms/IO/ReaderOf.cs
- src/Yaapii.Atoms/IO/TeeInputStream.cs
- src/Yaapii.Atoms/IO/TeeOutputStream.cs
- src/Yaapii.Atoms/IO/TeeReader.cs
- src/Yaapii.Atoms/IO/WriterAsOutputStream.cs
- src/Yaapii.Atoms/IO/WriterTo.cs
- src/Yaapii.Atoms/Text/TextOf.cs
- src/Yaapii.Atoms/Yaapii.Atoms.csproj
- tests/Yaapii.Atoms.Tests/Func/BiFuncWithFallbackTest.cs
- tests/Yaapii.Atoms.Tests/Yaapii.Atoms.Tests.csproj
#111 #106 #39 
BiFunc Method signature name has changed.
> I39 no docs

- src/Yaapii.Atoms/IO/ResourceNotFoundException.cs
- src/Yaapii.Atoms/IO/ResourceOf.cs
- tests/Yaapii.Atoms.Tests/IO/ResourceOfTest.cs
- tests/Yaapii.Atoms.Tests/IO/Resources/test.txt
- tests/Yaapii.Atoms.Tests/Yaapii.Atoms.Tests.csproj
> feat: add ResourceOf class

- src/Yaapii.Atoms/Text/SplitText.cs
- tests/Yaapii.Atoms.Tests/Text/SplitTextTest.cs
#119 
The SplitText ctors accepts a boolean to remove or don't remove empty strings.
> SplitText has an option to remove empty strings or not

- src/Yaapii.Atoms/Collection/NotEmpty.cs
- src/Yaapii.Atoms/Enumerable/NotEmpty.cs
- src/Yaapii.Atoms/List/NotEmpty.cs
- src/Yaapii.Atoms/Yaapii.Atoms.csproj
- tests/Yaapii.Atoms.Tests/Collection/NotEmptyTest.cs
- tests/Yaapii.Atoms.Tests/Enumerable/NotEmptyTest.cs
- tests/Yaapii.Atoms.Tests/List/NotEmptyTest.cs
#118 
NotEmpty decorator for
- IEnumerable
- IList
- ICollection
> NotEmpty decorator for enumerables, lists and collections

- src/Yaapii.Atoms/Enumerable/Distinct.cs
- src/Yaapii.Atoms/Enumerator/DistinctEnumerator.cs
- src/Yaapii.Atoms/Enumerator/LengthOfEnumerator.cs
- src/Yaapii.Atoms/Yaapii.Atoms.csproj
- tests/Yaapii.Atoms.Tests/Enumerable/DistinctTest.cs
- tests/Yaapii.Atoms.Tests/Enumerator/DistinctEnumeratorTest.cs
closes #150
see #150 
solved issue
> feat: add distinct enumerable

- build.cake
- src/Yaapii.Atoms/Enumerable/Distinct.cs
- src/Yaapii.Atoms/Enumerator/DistinctEnumerator.cs
- src/Yaapii.Atoms/Enumerator/LengthOfEnumerator.cs
- src/Yaapii.Atoms/Yaapii.Atoms.csproj
- tests/Yaapii.Atoms.Tests/Enumerable/DistinctTest.cs
- tests/Yaapii.Atoms.Tests/Enumerator/DistinctEnumeratorTest.cs
- tests/Yaapii.Atoms.Tests/Text/TextOfTest.cs
> I148 textof ctors

- src/Yaapii.Atoms/Text/FormattedText.cs
- tests/Yaapii.Atoms.Tests/Text/FormattedTextTest.cs
> I136 additional ctor formatted text

- src/Yaapii.Atoms/Number/NumberOf.cs
- tests/Yaapii.Atoms.Tests/Number/NumberOfTest.cs
> I140 additional ctors in number of

- src/Yaapii.Atoms/Enumerable/Contains.cs
- src/Yaapii.Atoms/Enumerator/ContainsEnumerator.cs
> Removed unnecessary type limitaion from Yaapii.Atoms.Enumerable.Contains

- src/Yaapii.Atoms/Enumerator/DistinctEnumerator.cs
- tests/Yaapii.Atoms.Tests/Enumerable/DistinctTest.cs
> i168 fix: distinct cant run twice with same result

- .github/ISSUE_TEMPLATE.md
- src/Yaapii.Atoms/Text/IsWhitespace.cs
- tests/Yaapii.Atoms.Tests/Text/IsWhitespaceTest.cs
#127 
renamed to IsWhitespace
Class IsBlank was renamed, builds will break.
> I127 rename is blank

- src/Yaapii.Atoms/IO/Directory.cs
- tests/Yaapii.Atoms.Tests/Bytes/Base64BytesTest.cs
- tests/Yaapii.Atoms.Tests/Collection/ArrayListAsCollectionTest.cs
- tests/Yaapii.Atoms.Tests/Enumerable/ArrayListAsEnumerableTest.cs
- tests/Yaapii.Atoms.Tests/Enumerable/DistinctTest.cs
- tests/Yaapii.Atoms.Tests/Enumerable/StickyEnumerableTests.cs
- tests/Yaapii.Atoms.Tests/Enumerator/DistinctEnumeratorTest.cs
- tests/Yaapii.Atoms.Tests/Func/ActionWithFallbackTest.cs
- tests/Yaapii.Atoms.Tests/Func/BiFuncWithFallbackTest.cs
- tests/Yaapii.Atoms.Tests/IO/DirectoryOfTests.cs
- tests/Yaapii.Atoms.Tests/IO/ResourceOfTest.cs
- tests/Yaapii.Atoms.Tests/Scalar/EachTests.cs
- tests/Yaapii.Atoms.Tests/Scalar/OrTests.cs
- tests/Yaapii.Atoms.Tests/Text/Base64DecodedTextTest.cs
- tests/Yaapii.Atoms.Tests/Text/EndsWithTests.cs
- tests/Yaapii.Atoms.Tests/Text/TextOfTest.cs
- tests/Yaapii.Atoms.Tests/Tidy.cs
#173 
Added DirectoryOf to IO
closes #173
> I173 directory

- src/Yaapii.Atoms/Enumerable/LengthOf.cs
- src/Yaapii.Atoms/IO/GZipInput.cs
- src/Yaapii.Atoms/IO/GZipOutput.cs
- src/Yaapii.Atoms/IO/InputAsBytes.cs
- src/Yaapii.Atoms/IO/LengthOf.cs
- tests/Yaapii.Atoms.Tests/IO/GZipInputTests.cs
- tests/Yaapii.Atoms.Tests/IO/GZipOutputTests.cs
> I176 zip inout

- tests/Yaapii.Atoms.Tests/Text/NotNullTextTests.cs
> Test: added NotNullText-Test

- README.md
Repo has Elegant Objects badge
> Add Elegant Objects badge

- src/Yaapii.Atoms/Enumerable/ItemAt.cs
- tests/Yaapii.Atoms.Tests/Enumerable/ItemAtTest.cs
closes #192
closes #192 
- [n] No
> feat: ItemAt result is sticky

- src/Yaapii.Atoms/Enumerable/ItemAt.cs
- tests/Yaapii.Atoms.Tests/Enumerable/ItemAtTest.cs
closes #184 
Item At has ctors for giving explicit Exceptions on fallback
> feat: ItemAt has ctors with Exception to throw on fallback

- src/Yaapii.Atoms/Text/ComparableText.cs
- tests/Yaapii.Atoms.Tests/Text/ComparableTextTests.cs
closes #204
closes #204 
closes #188
> feat: adds comparableTexts

- src/Yaapii.Atoms/IO/Zip.cs
- tests/Yaapii.Atoms.Tests/IO/ZipTest.cs
> I199 port class zip

- src/Yaapii.Atoms/Error/FailEmpty.cs
- src/Yaapii.Atoms/Error/FailEmptyOpt.cs
- src/Yaapii.Atoms/Error/FailNoNumber.cs
- src/Yaapii.Atoms/Error/FailNotNull.cs
- src/Yaapii.Atoms/Error/FailNull.cs
- src/Yaapii.Atoms/Error/FailNullOrEmpty.cs
- src/Yaapii.Atoms/Error/FailWhen.cs
- src/Yaapii.Atoms/Error/FailZero.cs
- tests/Yaapii.Atoms.Tests/Error/FailEmptyOptTests.cs
- tests/Yaapii.Atoms.Tests/Error/FailEmptyTests.cs
- tests/Yaapii.Atoms.Tests/Error/FailNoNumberTests.cs
- tests/Yaapii.Atoms.Tests/Error/FailNotNullTests.cs
- tests/Yaapii.Atoms.Tests/Error/FailNullOrEmptyTests.cs
- tests/Yaapii.Atoms.Tests/Error/FailNullTests.cs
- tests/Yaapii.Atoms.Tests/Error/FailWhenTests.cs
- tests/Yaapii.Atoms.Tests/Error/FailZeroTests.cs
closes #58
#58 
It's possible to inject an specific exception in the ctor's.
> Fail classes accepts an specific exception

- src/Yaapii.Atoms/Text/TextOf.cs
- tests/Yaapii.Atoms.Tests/Text/TextOfTest.cs
> I232 cultureinvariant

- src/Yaapii.Atoms/Enumerable/FirstOf.cs
- src/Yaapii.Atoms/Enumerable/LastOf.cs
- tests/Yaapii.Atoms.Tests/Enumerable/FirstOfTests.cs
- tests/Yaapii.Atoms.Tests/Enumerable/LastOfTests.cs
> feat: new classes FirstOf and LastOf in Enumerable

- src/Yaapii.Atoms/Map/MapEnvelope.cs
- tests/Yaapii.Atoms.Tests/Map/MapEnvelopeTest.cs
#238
MapEnvelope.TryGetValue don't fail with read only exception.
> I238 - Implement MapEnvelope.TryGetValue

- src/Yaapii.Atoms/Text/HexOf.cs
- tests/Yaapii.Atoms.Tests/Text/HexOfTest.cs
> i187 - Port class HexOf from cactoos

- src/Yaapii.Atoms/Scalar/And.cs
- src/Yaapii.Atoms/Scalar/Or.cs
- tests/Yaapii.Atoms.Tests/Scalar/AndTest.cs
- tests/Yaapii.Atoms.Tests/Scalar/OrTests.cs
closes #13
closes #161
Issues solved.
> New Ctor for And and Or classes and increase test coverage

- src/Yaapii.Atoms/IO/DigestEnvelope.cs
- src/Yaapii.Atoms/IO/Md5DigestOf.cs
- src/Yaapii.Atoms/IO/Sha1DigestOf.cs
- src/Yaapii.Atoms/IO/Sha256DigestOf.cs
- tests/Yaapii.Atoms.Tests/IO/Md5DigestOfTest.cs
- tests/Yaapii.Atoms.Tests/IO/Resources/digest-calculation.txt
- tests/Yaapii.Atoms.Tests/IO/Sha1DigestOfTest.cs
- tests/Yaapii.Atoms.Tests/IO/Sha256DigestOfTest.cs
- tests/Yaapii.Atoms.Tests/Yaapii.Atoms.Tests.csproj
> I196 - port Sha1DigestOf, Sha256DigestOf, Md5DigestOf

- src/Yaapii.Atoms/IO/TempDirectory.cs
- tests/Yaapii.Atoms.Tests/Bytes/BytesBase64Test.cs
- tests/Yaapii.Atoms.Tests/Collection/FilteredTest.cs
- tests/Yaapii.Atoms.Tests/Collection/SyncCollectionTest.cs
- tests/Yaapii.Atoms.Tests/IO/TempDirectoryTests.cs
closes #244
New disposable class `TempDirectory` and tests.
> New class TempDirectory

- src/Yaapii.Atoms/Collection/CollectionEnvelope.cs
- src/Yaapii.Atoms/Enumerable/EnumerableEnvelope.cs
- src/Yaapii.Atoms/IO/DigestEnvelope.cs
- src/Yaapii.Atoms/List/ListEnvelope.cs
- src/Yaapii.Atoms/Map/MapEnvelope.cs
- src/Yaapii.Atoms/Number/NumberEnvelope.cs
- tests/Yaapii.Atoms.Tests/Map/MapEnvelopeTest.cs
> fi: envelopes must be abstract and have public ctors

- src/Yaapii.Atoms/Scalar/FirstOf.cs
- src/Yaapii.Atoms/Scalar/ItemAt.cs
- src/Yaapii.Atoms/Scalar/LastOf.cs
- src/Yaapii.Atoms/Scalar/Max.cs
- src/Yaapii.Atoms/Scalar/Min.cs
- tests/Yaapii.Atoms.Tests/Collection/ReversedTest.cs
- tests/Yaapii.Atoms.Tests/List/MappedTest.cs
> fix: restore old namespaces for ItemAt

- src/Yaapii.Atoms/IO/TempFile.cs
- tests/Yaapii.Atoms.Tests/IO/TempFileTest.cs
> i195 - Port class TempFile

- src/Yaapii.Atoms/Bytes/HexBytes.cs
- tests/Yaapii.Atoms.Tests/Bytes/HexBytesTest.cs
> feat: add HexBytes class and test

- .github/PULL_REQUEST_TEMPLATE.md
- src/Yaapii.Atoms/Map/MapOf.cs
- src/Yaapii.Atoms/Map/SolidMap.cs
- src/Yaapii.Atoms/Map/StickyMap.cs
- src/Yaapii.Atoms/Map/StringMap.cs
- tests/Yaapii.Atoms.Tests/Map/MapOfTest.cs
- tests/Yaapii.Atoms.Tests/Map/StringMapTests.cs
> feat: new type StringMap and ctors for existing maps accepting sequences

- src/Yaapii.Atoms/Func/BowAction.cs
- tests/Yaapii.Atoms.Tests/Func/BowActionTests.cs
> feat: new BowFunc

- src/Yaapii.Atoms/IO/TempDirectory.cs
- tests/Yaapii.Atoms.Tests/IO/TempDirectoryTests.cs
> feat: tempdirectory works with write protected files

- src/Yaapii.Atoms/Enumerable/Strings.cs
- src/Yaapii.Atoms/Map/StringMap.cs
- tests/Yaapii.Atoms.Tests/Enumerable/StringsTests.cs
> fix: remove doubled ctors

- src/Yaapii.Atoms/Scalar/FirstOf.cs
- tests/Yaapii.Atoms.Tests/Scalar/FirstOfTests.cs
> fix: firstof uses condition

- src/Yaapii.Atoms/IO/InputOf.cs
> refactor: InputOf has scalar fileInfo

- src/Yaapii.Atoms/Text/TextOf.cs
- tests/Yaapii.Atoms.Tests/Text/TextOfTest.cs
> i298 add ctor to TextOf which takes a long

- src/Yaapii.Atoms/Map/StringMap.cs
> i297 remove ctor taking params KeyValuePair<string, string>[] from StringMap

- src/Yaapii.Atoms/Map/StringMap.cs
- tests/Yaapii.Atoms.Tests/Map/StringMapTests.cs
> feat: add merge ctor to StringMap

- src/Yaapii.Atoms/Bytes/BytesOf.cs
- tests/Yaapii.Atoms.Tests/Bytes/BytesOfTest.cs
> i293 add ctors taking int, long, float or double to BytesOf

- src/Yaapii.Atoms/Enumerable/Replaced.cs
- tests/Yaapii.Atoms.Tests/Enumerable/ReplacedTest.cs
> I145 add new ctor to enumerable replaced

- src/Yaapii.Atoms/Error/FailAlways.cs
- src/Yaapii.Atoms/Error/FailEmpty.cs
- src/Yaapii.Atoms/Error/FailNoNumber.cs
- src/Yaapii.Atoms/Error/FailNotNull.cs
- src/Yaapii.Atoms/Error/FailNull.cs
- src/Yaapii.Atoms/Error/FailNullOrEmpty.cs
- src/Yaapii.Atoms/Error/FailWhen.cs
- src/Yaapii.Atoms/Error/FailZero.cs
> docs (Error): update xml class documentation for Fail classes

- README.md
> i320 rename Limited to HeadOf in the readme

- src/Yaapii.Atoms/IO/Directory.cs
- tests/Yaapii.Atoms.Tests/IO/DirectoryOfTests.cs
> I182 extend directory class to optionally enumerate all files from sub directories

- build.cake
Due to an issue in Cake.CodeCov 0.6.0 the Code Coverage Report can't be uploaded.
Pin CodeCov Addin version 0.5.0 fixes the upload issue.
> Pin Cake.CodeCov addin to version 0.5.0

- src/Yaapii.Atoms/Time/DateOf.cs
- tests/Yaapii.Atoms.Tests/Time/DateOfTest.cs
> i275 add new pattern to DateOf so it parses "Fri, 29 Mar 2019 12:506 GMT" correctly

- src/Yaapii.Atoms/Text/IsWhitespace.cs
- tests/Yaapii.Atoms.Tests/Text/IsWhitespaceTest.cs
> feat: add ctor taking a string to IsWhitespace

- src/Yaapii.Atoms/Error/FailWhen.cs
- tests/Yaapii.Atoms.Tests/Error/FailWhenTests.cs
> i260 add ctor taking bool and Exception to FailWhen

- src/Yaapii.Atoms/IO/InputOf.cs
- tests/Yaapii.Atoms.Tests/IO/InputOfTest.cs
- tests/Yaapii.Atoms.Tests/IO/TeeInputTest.cs
> i214 TeeInput w/two Uri parameters returns a misleading exception

- src/Yaapii.Atoms/Func/BowAction.cs
- src/Yaapii.Atoms/Func/BowFunc.cs
- tests/Yaapii.Atoms.Tests/Func/BowFuncTests.cs
> I322 fix bow action

- src/Yaapii.Atoms/Number/IsNumber.cs
- tests/Yaapii.Atoms.Tests/Number/IsNumberTests.cs
> i229 add class IsNumber

- src/Yaapii.Atoms/Scalar/Sticky.cs
- tests/Yaapii.Atoms.Tests/Scalar/StickyTest.cs
closes #330 
Reloadcondition is not a IFunc anymore.
> Improve sticky performance

- src/Yaapii.Atoms/Text/TextOf.cs
- tests/Yaapii.Atoms.Tests/Text/TextOfTest.cs
> TextOf with ctor, that takes a Stream

- src/Yaapii.Atoms/Scalar/BitAt.cs
- tests/Yaapii.Atoms.Tests/Scalar/BitAtTest.cs
close #326 
- new `BitAt()` implements `IScalar<byte>`
> New BitAt to get a bit from IBytes

- tests/Yaapii.Atoms.Tests/Collection/MappedTest.cs
One test is broken, see issue
closes #349
> fix: use comparable class to repair test

- src/Yaapii.Atoms/Text/Paragraph.cs
- tests/Yaapii.Atoms.Tests/Text/ParagraphTest.cs
> Text: implement Paragraph

- src/Yaapii.Atoms/Map/Sorted.cs
- tests/Yaapii.Atoms.Tests/Map/SortedTest.cs
> feat(map): add Sorted

- src/Yaapii.Atoms/Map/Map.Envelope.cs
- tests/Yaapii.Atoms.Tests/Map/MapEnvelopeTest.cs
fixes #362
Missing keys are normally handled by `KeyNotFoundException` and are now being handled as `ArgumentException` which might to be catched differently.
> fix(Map): include desired key in the missing key exception

- tests/Yaapii.Atoms.Tests/IO/DirectoryOfTests.cs
- tests/Yaapii.Atoms.Tests/IO/ZipTest.cs
fixes #381
CI should also build and test on Linux (or maybe macOS) when someone is using Atoms in production in a *nix environment.
Currently the tests are only automated with AppVeyor on Windows maschines.
> Use Path methods instead of hardcoded paths

- src/Yaapii.Atoms/Map/Joined.cs
- src/Yaapii.Atoms/Map/LiveMap.cs
- src/Yaapii.Atoms/Map/MapInputEnvelope.cs
- src/Yaapii.Atoms/Map/Solid.cs
- src/Yaapii.Atoms/Map/Synced.cs
- tests/Yaapii.Atoms.Tests/Map/LiveMapTests.cs
closes #385 
LiveMap ctors have changed to only accept live objects.
> Prevent LiveMap misuse

- src/Yaapii.Atoms/Bytes/Base64Bytes.cs
- src/Yaapii.Atoms/Bytes/BytesBase64.cs
- src/Yaapii.Atoms/Bytes/BytesEqual.cs
- src/Yaapii.Atoms/Bytes/BytesOf.cs
- src/Yaapii.Atoms/Bytes/HexBytes.cs
- src/Yaapii.Atoms/Bytes/InputAsBytes.cs
- src/Yaapii.Atoms/Bytes/LiveBytes.cs
- tests/Yaapii.Atoms.Tests/Bytes/LiveBytesTest.cs
> Make Byte classes sticky by default

- src/Yaapii.Atoms/IO/AppendTo.cs
- src/Yaapii.Atoms/Primitives/CharOf.cs
> Make CharOf sticky

- src/Yaapii.Atoms/Func/BowAction.cs
- src/Yaapii.Atoms/Func/BowFunc.cs
BowAction uses a while loop to wait
BowAction uses task.Wait
closes #402
> Improve BowAction implementation

- .github/ISSUE_TEMPLATE.md
- src/Yaapii.Atoms/Map/VersionMap.cs
- tests/Yaapii.Atoms.Tests/Map/VersionMapTests.cs
We have a version map which can match Version ranges.
> Add a VersionMap

- src/Yaapii.Atoms/Text/TextBase64.cs
- tests/Yaapii.Atoms.Tests/Text/TextBase64Tests.cs
> Fix TextBase64 to encode strings properly

- src/Yaapii.Atoms/Text/Synced.cs
- tests/Yaapii.Atoms.Tests/Text/SyncedTest.cs
> feat(text): implement Synced

- src/Yaapii.Atoms/Text/Strict.cs
- tests/Yaapii.Atoms.Tests/Text/StrictTest.cs
> Add strict text class

- src/Yaapii.Atoms/Map/Joined.cs
- src/Yaapii.Atoms/Map/LiveMap.cs
- src/Yaapii.Atoms/Map/MapInputEnvelope.cs
- src/Yaapii.Atoms/Map/MapInputOf.cs
- src/Yaapii.Atoms/Map/MapOf.cs
- tests/Yaapii.Atoms.Tests/Map/MapOfTest.cs
- tests/Yaapii.Atoms.Tests/Map/VersionMapTests.cs
> Prevent building all values in a Map

- src/Yaapii.Atoms/Map/Joined.cs
- tests/Yaapii.Atoms.Tests/Map/JoinedMapTests.cs
> Prevent Map.Joined from building all lazy values

- src/Yaapii.Atoms/Map/MapOf.cs
- tests/Yaapii.Atoms.Tests/Map/MapOfTest.cs
> Revert incompatible changes in MapOf

- src/Yaapii.Atoms/Map/MapOf.cs
- tests/Yaapii.Atoms.Tests/Map/MapOfTest.cs
> MapOf works with empty list of strings

- src/Yaapii.Atoms/IO/HeadInputStream.cs
- src/Yaapii.Atoms/IO/HeadOf.cs
- tests/Yaapii.Atoms.Tests/IO/HeadInputStreamTest.cs
- tests/Yaapii.Atoms.Tests/IO/HeadOfTest.cs
#197 
There exists a class HeadInputStream and HeadOf which reads the head of an input.
closes #197
> Port class HeadInput/ HeadOf

- src/Yaapii.Atoms/Number/Similar.cs
- tests/Yaapii.Atoms.Tests/Number/SimilarTest.cs
#334 
There exists a class which checks if two INumbers are similar in a given accuracy.
closes #334
> Add a Similar class for INumber

- src/Yaapii.Atoms/Enumerable/Divergency.cs
- src/Yaapii.Atoms/Enumerator/Logging.cs
- src/Yaapii.Atoms/Func/BowAction.cs
- src/Yaapii.Atoms/Func/BowFunc.cs
- src/Yaapii.Atoms/IKvp.cs
- src/Yaapii.Atoms/IMapInput.cs
- src/Yaapii.Atoms/IO/Directory.cs
- src/Yaapii.Atoms/Map/FallbackMap.cs
- src/Yaapii.Atoms/Map/FkKvp.cs
- src/Yaapii.Atoms/Map/Sorted.cs
- src/Yaapii.Atoms/Map/VersionMap.cs
- src/Yaapii.Atoms/Scalar/BitAt.cs
- src/Yaapii.Atoms/Scalar/NoNull.cs
- src/Yaapii.Atoms/Scalar/ParallelAnd.cs
- src/Yaapii.Atoms/Scalar/ScalarEnvelope.cs
- src/Yaapii.Atoms/Text/Paragraph.cs
- src/Yaapii.Atoms/Text/Strict.cs
- tests/Yaapii.Atoms.Tests/IO/ZipMappedPathsTests.cs
- tests/Yaapii.Atoms.Tests/Map/JoinedMapTests.cs
- tests/Yaapii.Atoms.Tests/Map/KvpOfTests.cs
- tests/Yaapii.Atoms.Tests/Map/LazyDictTests.cs
- tests/Yaapii.Atoms.Tests/Map/SortedTest.cs
- tests/Yaapii.Atoms.Tests/Map/VersionMapTests.cs
- tests/Yaapii.Atoms.Tests/Scalar/BitAtTest.cs
- tests/Yaapii.Atoms.Tests/Scalar/LiveTests.cs
- tests/Yaapii.Atoms.Tests/Scalar/ParallelAndTest.cs
- tests/Yaapii.Atoms.Tests/Text/ParagraphTest.cs
- tests/Yaapii.Atoms.Tests/Text/StrictTest.cs
- tests/Yaapii.Atoms.Tests/Time/DateAsTextTest.cs
#436 
All classes have copyright header.
closes #436
> Add copyright header

- src/Yaapii.Atoms/IO/LoggingOutput.cs
- src/Yaapii.Atoms/IO/LoggingOutputStream.cs
- tests/Yaapii.Atoms.Tests/Assets/Txt/large-text.txt
- tests/Yaapii.Atoms.Tests/IO/LoggingOutoutTest.cs
- tests/Yaapii.Atoms.Tests/IO/LoggingOutputTest.cs
- tests/Yaapii.Atoms.Tests/Yaapii.Atoms.Tests.csproj
#201 
Port the class LoggingOutput and LoggingOutputStream.
closes #201
> Port class LoggingOutput

- src/Yaapii.Atoms/IO/MemoryInput.cs
- tests/Yaapii.Atoms.Tests/IO/MemoryInputTest.cs
#347 
There exists a class that implements an Input with a sticky stream.
closes #347
> Add memorizing input

- src/Yaapii.Atoms/IO/LoggingInput.cs
- src/Yaapii.Atoms/IO/LoggingInputStream.cs
- tests/Yaapii.Atoms.Tests/IO/LoggingInputStreamTest.cs
- tests/Yaapii.Atoms.Tests/IO/LoggingInputTest.cs
#200 
There exists a class which loggs the current action while reading an input.
closes #200
> Port class LoggingInput

- src/Yaapii.Atoms/Func/BowAction.cs
- src/Yaapii.Atoms/Func/BowFunc.cs
see #456
BowAction and BowFunc use Task.Delay instead of Thread.Sleep to avoid thread starvation.
closes #456
> Replace Thread.Sleep with Task.Delay

- src/Yaapii.Atoms/Enumerator/Repeated.cs
- tests/Yaapii.Atoms.Tests/Enumerator/RepeatedTest.cs
Repeated enumerator does not reject negative amount of repeats.
closes #450
> Reject negative repeats in Repeated Enumerator

- src/Yaapii.Atoms/Func/BowAction.cs
> fix: make BowFunc threadsafe

- src/Yaapii.Atoms/Yaapii.Atoms.csproj
> build(dotnet): use PackageLicenseExpression

- src/Yaapii.Atoms/Enumerable/Filtered.cs
- src/Yaapii.Atoms/Enumerable/ManyEnvelope.cs
- src/Yaapii.Atoms/Enumerable/Mapped.cs
- src/Yaapii.Atoms/Lists/ListEnvelope.cs
- src/Yaapii.Atoms/Lists/LiveList.cs
- src/Yaapii.Atoms/Lists/SyncList.cs
- tests/Yaapii.Atoms.Tests/Lists/LiveListTest.cs
fixes #470 
Add missing constructors existing in v2.1.3
> Undo breaking change in versions 2.1.3 <-> 2.2.1

- build.cake
- src/Yaapii.Atoms/Yaapii.Atoms.csproj
#475 
Atoms only target netstandard2.0.
> Removes Multitarget Frameworks and fixes Package Version

- src/Yaapii.Atoms/Lists/LiveList.cs
> Breaking Change in LiveList version 2.3.0

- src/Yaapii.Atoms/Lists/ListEnvelope.cs
- tests/Yaapii.Atoms.Tests/Lists/LiveListTest.cs
> fix listenvelope to move enumerator correctly

- src/Yaapii.Atoms/Enumerable/ExactAmount.cs
- src/Yaapii.Atoms/Enumerable/LengthOf.cs
- src/Yaapii.Atoms/Enumerable/LessThan.cs
- src/Yaapii.Atoms/Enumerable/MoreThan.cs
- src/Yaapii.Atoms/Scalar/ScalarOf.cs
- tests/Yaapii.Atoms.Tests/Enumerable/ExactAmountTests.cs
- tests/Yaapii.Atoms.Tests/Enumerable/LessThanTests.cs
- tests/Yaapii.Atoms.Tests/Enumerable/MoreThanTests.cs
Closes #490 
We have objects to make conditions based on enumerables sizes more efficiently.
> feat: add more, less and exact for enumerables

- src/Yaapii.Atoms/Text/SubText.cs
- tests/Yaapii.Atoms.Tests/Text/SubTextTest.cs
#465 
renamed parameter ent to len, added test for SubText
> Adds Tests for SubText

- src/Yaapii.Atoms/IO/WriterAsOutputStream.cs
- tests/Yaapii.Atoms.Tests/IO/WriterAsOutputStreamTest.cs
> Adds Tests for WriterAsOutputStream

- src/Yaapii.Atoms/Enumerable/Distinct.cs
- src/Yaapii.Atoms/Enumerator/Distinct.cs
- tests/Yaapii.Atoms.Tests/Enumerable/DistinctTest.cs
> add comparison for distinct class

- src/Yaapii.Atoms/Map/VersionMap.cs
- tests/Yaapii.Atoms.Tests/Map/VersionMapTests.cs
> Correct VersionMap behaviour with 2 or 3 digit versions

- src/Yaapii.Atoms/Enumerable/SortedBy.cs
- src/Yaapii.Atoms/Enumerator/SortedBy.cs
- tests/Yaapii.Atoms.Tests/Enumerable/SortedByTests.cs
> add sortedBy enumerable

- appveyor.yml
- src/Yaapii.Atoms/Text/Trimmed.cs
- tests/Yaapii.Atoms.Tests/Text/TrimmedTest.cs
#520 
The class has consistent behaviour in trimming a given text.
> Trimmed Text has consistent behaviour among Ctors

- src/Yaapii.Atoms/Text/TextOf.cs
- tests/Yaapii.Atoms.Tests/Text/TextOfTest.cs
> Add bool constructor to TextOf

- src/Yaapii.Atoms/Bytes/BytesOf.cs
- tests/Yaapii.Atoms.Tests/Bytes/BytesOfTest.cs
> Use correct encoding in BytesOf

- build.cake
> Only validate credentials on tags

- src/Yaapii.Atoms/Enumerable/Union.cs
- tests/Yaapii.Atoms.Tests/Enumerable/UnionTests.cs
> fix Union class

- src/Yaapii.Atoms/Enumerable/ManyEnvelope.cs
> Fix caching in ManyEnvelope

- tests/Yaapii.Atoms.Tests/Enumerable/ManyEnvelopeTests.cs
- The fix introduced in #573 does not have unit tests.
- Add tests.
- related to #572 
- related to #573
> Add tests missing in PR #573
